# Generated by Django 3.1.4 on 2021-02-07 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('game_name', models.CharField(max_length=255)),
                ('created_ad', models.DateTimeField()),
                ('is_deleted', models.BooleanField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.group')),
                ('user_statistics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.statistics')),
            ],
        ),
        migrations.CreateModel(
            name='GroupRelationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.group')),
                ('user_statistics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.statistics')),
            ],
        ),
    ]
