# Generated by Django 3.1.4 on 2021-02-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_group_grouprelationships_invitations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_ad',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
