# Generated by Django 3.1.4 on 2021-02-07 13:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_invitations_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitations',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
