# Generated by Django 3.1.4 on 2021-02-07 16:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20210207_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitations',
            name='status',
        ),
        migrations.AddField(
            model_name='grouprelationships',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
