# Generated by Django 3.1.4 on 2021-02-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20210207_1755'),
    ]

    operations = [
        migrations.RunSQL('RAW SQL CODE')
    ]
